### ISSUE TITLE
Supports use as a function

### ISSUE THREAD

**Issue by JackSho** [robertluo/fun-map#59]
## Purpose

fun-map has replaced clojure map in most situations, except for one case where it cannot be used as a function, such as the expected call

```clojure
(def m (fun-map {:a 1}))
(m :a)   ;; => 1
(m :b 2) ;; => 2
```

but actually get an error: `class robertluo.fun_map.core.DelegatedMap cannot be cast to class clojure.lang.IFn`.

**Comment by robertluo** [comment]
It is a good addition. Could you send me a PR for this?
